<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * P1-11: Offline event buffer.
 *
 * When a branch controller is offline (no internet), it stores events locally
 * and replays them once connectivity returns. This table is the cloud-side
 * inbox for those replayed events:
 *
 *   1. Controller reconnects → publishes to MQTT topic sync/{device_id}/replay
 *      with a JSON payload containing one or more buffered events.
 *   2. Backend ingests each event into device_event_buffers (status=pending).
 *   3. SyncOfflineEventsJob processes pending rows in the original chronological
 *      order, dispatching them through the same handlers used for live events
 *      (door, button, vault, fingerprint, …).
 *   4. Idempotency: each row carries the device-side event UUID. Re-replays
 *      are deduplicated by (device_id, source_event_id).
 */
return new class extends Migration {
    public function up(): void
    {
        Schema::create('device_event_buffers', function (Blueprint $table) {
            $table->uuid('id')->primary();

            // Originating device (controller). Indexed for batch processing per device.
            $table->foreignUuid('device_id')
                ->constrained('devices')
                ->cascadeOnDelete();

            $table->foreignUuid('vault_id')
                ->nullable()
                ->constrained('vaults')
                ->nullOnDelete();

            // Original event UUID generated by the controller. Used for dedup.
            $table->uuid('source_event_id');

            // The MQTT topic this event would have been published on.
            $table->string('topic');

            // The event type / category (door_opened, fingerprint_scan, …).
            $table->string('event_type', 64);

            // Full original payload as JSON.
            $table->jsonb('payload');

            // When the event actually happened on the controller.
            $table->timestamp('occurred_at');

            // When the controller managed to upload this event to the cloud.
            $table->timestamp('uploaded_at');

            // Processing pipeline state: pending | processing | processed | failed | skipped.
            $table->string('status', 16)->default('pending');

            // Number of processing attempts.
            $table->unsignedTinyInteger('attempts')->default(0);

            // Last error message if processing failed.
            $table->text('last_error')->nullable();

            // When processing finished (success or final failure).
            $table->timestamp('processed_at')->nullable();

            $table->timestamps();

            // Dedup: the same controller cannot upload the same source_event_id twice.
            $table->unique(['device_id', 'source_event_id'], 'device_event_buffers_dedup');

            // Common access patterns.
            $table->index(['status', 'occurred_at']);
            $table->index('device_id');
            $table->index('vault_id');
            $table->index('event_type');
            $table->index('uploaded_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('device_event_buffers');
    }
};
